### ISSUE TITLE
How to exit the application within code

### ISSUE THREAD

**Issue by LGFae** [MatchaChoco010/egui-ash#2]
Hello! Thanks a lot for this, I was just struggling with exactly the problem of adding an UI to a game I am making in my spare time with Ash.

However, I can't seem to figure out how to exit the application within the code. For example, when the user presses the Escape key.

From what I've managed to tell from the current documentation and general state of the crate, this currently seems impossible.

**Comment by MatchaChoco010** [comment]
Hello! Thanks for your interest in this crate!

As you pointed out, 0.2.0 could not terminate the app from the app code.
So, I have just released 0.3.0 which adds the ability to terminate the app from the code.

You can receive `exit_signal` from `CreationContext`.
By `exit_signal.send(exit_code);` you can exit the application with any exit code.

I have added an implementation of exit with ESC key to egui_ash_simple of example, so please check it out.

```
cargo run --release --example egui_ash_simple
```
