### ISSUE TITLE
How does persistence work?

### ISSUE THREAD

**Issue by tyrypyrking** [MatchaChoco010/egui-ash#3]
There seem to be no legal way to get storage::Storage to access (get/set)_value outside of the crate. I'd greatly appreciate some pointers in the right direction because docs didn't help a single bit.

**Comment by MatchaChoco010** [comment]
The persistence feature is used to save and restore the memory state and window size used internally.
For example, setting `persistent_windows` and `persistent_egui_memory` to `true` in RunOption will save the window size and position, scale factor, etc.

Note, however, that there is currently a bug in egui itself in saving the scale factor and window position.
https://github.com/emilk/egui/issues/3797

persistence featureI did not envision using it to save the user's state.
If users want to save values, they should serialize the values they want to save themselves into a file or something and load it at startup.

I have added a description of the persistence feature in README.md.

If you want the persistence feature to save and restore user-defined values as well, PR is welcome.

**Comment by tyrypyrking** [comment]
Then I guessed right. I'm already cooking up a PR following eframe as an API example to allow for faster transition, but with minimal change to the inner workings of the crate.

**Comment by tyrypyrking** [comment]
Issue can be considered resolved. Pull request is #4 . Unless storage was accessed not through CreationContext migration (from eframe to egui-ash) for this feature shouldn't require any changes.
